// <auto-generated/>
// <copyright file="202409071106475_first_migration.cs" company="Transilvania University of Brasov">
// Copyright © 2024 Bosnea Marian-Daniel. All rights reserved.
// </copyright>

namespace DataMapper.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class first_migration : DbMigration
    {
        public override void Up()
        {
            this.CreateTable(
                "dbo.Auctions",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        StartDate = c.DateTime(nullable: false),
                        EndDate = c.DateTime(nullable: false),
                        StartingPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Currency = c.String(nullable: false, maxLength: 3),
                        IsCompleted = c.Boolean(nullable: false),
                        Product_Id = c.Int(nullable: false),
                        Seller_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Products", t => t.Product_Id, cascadeDelete: true)
                .ForeignKey("dbo.People", t => t.Seller_Id, cascadeDelete: true)
                .Index(t => t.Product_Id)
                .Index(t => t.Seller_Id);
            
            this.CreateTable(
                "dbo.Bids",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Currency = c.String(nullable: false, maxLength: 3),
                        BidTime = c.DateTime(nullable: false),
                        Bidder_Id = c.Int(),
                        Auction_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.People", t => t.Bidder_Id)
                .ForeignKey("dbo.Auctions", t => t.Auction_Id)
                .Index(t => t.Bidder_Id)
                .Index(t => t.Auction_Id);
            
            this.CreateTable(
                "dbo.People",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(nullable: false, maxLength: 100),
                        Score = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Role = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            this.CreateTable(
                "dbo.Products",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(nullable: false, maxLength: 200),
                        Description = c.String(nullable: false, maxLength: 1000),
                    })
                .PrimaryKey(t => t.Id);
            
            this.CreateTable(
                "dbo.Categories",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(nullable: false, maxLength: 100),
                        Product_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Products", t => t.Product_Id)
                .Index(t => t.Product_Id);
            
            this.CreateTable(
                "dbo.CategoryCategories",
                c => new
                    {
                        Category_Id = c.Int(nullable: false),
                        Category_Id1 = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.Category_Id, t.Category_Id1 })
                .ForeignKey("dbo.Categories", t => t.Category_Id)
                .ForeignKey("dbo.Categories", t => t.Category_Id1)
                .Index(t => t.Category_Id)
                .Index(t => t.Category_Id1);
            
        }
        
        public override void Down()
        {
            this.DropForeignKey("dbo.Auctions", "Seller_Id", "dbo.People");
            this.DropForeignKey("dbo.Auctions", "Product_Id", "dbo.Products");
            this.DropForeignKey("dbo.Categories", "Product_Id", "dbo.Products");
            this.DropForeignKey("dbo.CategoryCategories", "Category_Id1", "dbo.Categories");
            this.DropForeignKey("dbo.CategoryCategories", "Category_Id", "dbo.Categories");
            this.DropForeignKey("dbo.Bids", "Auction_Id", "dbo.Auctions");
            this.DropForeignKey("dbo.Bids", "Bidder_Id", "dbo.People");
            this.DropIndex("dbo.CategoryCategories", new[] { "Category_Id1" });
            this.DropIndex("dbo.CategoryCategories", new[] { "Category_Id" });
            this.DropIndex("dbo.Categories", new[] { "Product_Id" });
            this.DropIndex("dbo.Bids", new[] { "Auction_Id" });
            this.DropIndex("dbo.Bids", new[] { "Bidder_Id" });
            this.DropIndex("dbo.Auctions", new[] { "Seller_Id" });
            this.DropIndex("dbo.Auctions", new[] { "Product_Id" });
            this.DropTable("dbo.CategoryCategories");
            this.DropTable("dbo.Categories");
            this.DropTable("dbo.Products");
            this.DropTable("dbo.People");
            this.DropTable("dbo.Bids");
            this.DropTable("dbo.Auctions");
        }
    }
}
